language: python
python:
- '2.7'
services:
- postgresql
addons:
  postgresql: '9.4'
script:
- export LANG=en_US.UTF-8
- export WEB2PY_CONFIG=test
- export TEST_DBURL=postgres://postgres:@localhost/runestone_test
- wget https://mdipierro.pythonanywhere.com/examples/static/web2py_src.zip
- unzip web2py_src.zip
- cd web2py/applications
- ln -s ../../ runestone
- cd runestone
- mkdir private
- echo "sha512:16492eda-ba33-48d4-8748-98d9bbdf8d33" > private/auth.key
- cd books
- git clone https://github.com/RunestoneInteractive/thinkcspy.git
- cd ..
- cd tests
- "./run_tests.sh"
notifications:
  slack:
    secure: OfeZ/+YHpSl7GNFkzEKu0uObuMdymKmDEeDyfB++RaglalcgkDQAqrCPx+YVw6brXOHGeC6BkGJe/Fs143Ai8/yf38nMmZg/dej5nLgZNST67jWaapIydx5QeuCrsRKvUP+z6yEYoBkYXTsYPyTiKGGsyzvX6dimZRT4nD8qrv0=
