version: '3'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: 'runestone'
      POSTGRES_USER: 'runestone'
      POSTGRES_DB: 'runestone'

  redis:
    image: redis

  jobe:
    image: trampgeek/jobeinabox:latest

  runestone:
    image: runestone/server
    restart: always
    #command: tail -F peanutbutter
    volumes:
      - ./:/srv/web2py/applications/runestone
    links:
      - db
      - redis
      - jobe
    ports:
      - "80:80"
      - "443:443"
    environment:
      POSTGRES_PASSWORD: 'runestone'
      POSTGRES_USER: 'runestone'
      POSTGRES_DB: 'runestone'
      WEB2PY_CONFIG: 'development'
      WEB2PY_MIGRATE: 'Yes'
      DBURL: 'postgresql://runestone:${POSTGRES_PASSWORD}@db/runestone'
      DEV_DBURL: 'postgresql://runestone:${POSTGRES_PASSWORD}@db/runestone'
      TEST_DBURL: 'postgresql://runestone:${POSTGRES_PASSWORD}@db/runestone_test'
      REDIS_URI: 'redis://redis:6379/0'
      RUNESTONE_HOST: '${RUNESTONE_HOST}'
      CERTBOT_EMAIL: '${CERTBOT_EMAIL}'
