# *****************************************************
# |docname| - Configure containerize Docker application
# *****************************************************
version: '3'

services:
  db:
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}

  redis:
    image: redis
    ports:
      - 6379:6379

  jobe:
    image: runestone/jobeinabox
    build: ./jobeinabox/
    volumes:
      - ./jobeinabox/files:/usr/local/lib/java

  runestone:
    image: runestone/server
    restart: always
    volumes:
      # This must agree with ``$RUNESTONE_PATH`` in the `Dockerfile`. There's no easy way to share this automatically.
      - ./:/srv/web2py/applications/runestone
      # For certbot, store certificates outside the (ephemeral) write layer.
      - ./docker/letsencrypt:/etc/letsencrypt
    links:
      - db
      - redis
      - jobe
    ports:
      - "80:80"
      - "443:443"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      WEB2PY_CONFIG: ${SERVER_CONFIG}
      BOOK_SERVER_CONFIG: ${SERVER_CONFIG}
      WEB2PY_MIGRATE: 'Yes'
      DBURL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}'
      DEV_DBURL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}_dev'
      TEST_DBURL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}_test'
      REDIS_URI: 'redis://redis:6379/0'
      RUNESTONE_HOST: '${RUNESTONE_HOST}'
      CERTBOT_EMAIL: '${CERTBOT_EMAIL}'
