version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 'runestone'
      POSTGRES_USER: 'runestone'
      POSTGRES_DB: 'runestone'

  runestone:
    image: runestone/server
    restart: always
    #command: tail -F peanutbutter
    volumes:
      - ./:/srv/web2py/applications/runestone
    links:
      - db
    ports:
      - "80:80"
    environment:
      POSTGRES_PASSWORD: 'runestone'
      POSTGRES_USER: 'runestone'
      POSTGRES_DB: 'runestone'
      WEB2PY_CONFIG: 'development'
      WEB2PY_MIGRATE: 'Yes'
      DBURL: 'postgresql://runestone:${POSTGRES_PASSWORD}@db/runestone'
      DEV_DBURL: 'postgresql://runestone:${POSTGRES_PASSWORD}@db/runestone'
      TEST_DBURL: 'postgresql://runestone:${POSTGRES_PASSWORD}@db/runestone_test'
      RUNESTONE_HOST: '${RUNESTONE_HOST}'
